### ISSUE TITLE
Please make this repository private

### ISSUE THREAD

**Issue by cwelch-gatech** [brymon68/cs_6250#1]
We understand wanting to share your accomplishments of finding solutions to course materials. We ask that you make this repository private so that we can maintain the high caliber of learning and protect the value of the degree. When students and employers find that course solutions are easily found, it can raise concerns if the material is really being learned. We have found students who have copied portions of code they found from GitHub and submitted it as their own work. By making the repository private, we can ensure that current students are unable to use your work as their own. We understand that employers like to review students' code, so an option is to share the code by inviting them to the private repository.

**Comment by brymon68** [comment]
@cwelch-gatech  - Thanks for contacting me though, I do believe this issue you have submitted is [ automated](https://github.com/cwelch-gatech/APIIssueTest/issues) and are probably not monitoring responses. None the less. 

Over the past few years, I've been contacted multiple times to make the public repositories containing my coursework, assignments, documents etc. that I created as a student at Georgia Tech, private. I graduated in Spring of 2019 and I believe I took CS-6250 in 2017.  At this point, these assignments are roughly 6 years old. I have a couple points that I will once again address as the last person who contacted me, threatened to report me to my then employer and the Office of Integrity at Georgia Tech (which didnt make sense given I had already graduated, years previous). 

1. By open-sourcing the work I created while attending Georgia Tech, I am actually making it **_easier_** for you to verify whether a future student's work has plagiarized mine or not. I don't get why you or the others that have previously contacted me fail to see this point. If someone had improperly obtained my coursework and it were not publicly open-sourced, you would have no way of knowing whether that work was theirs or mine. 
2. If the Professor / GAs of CS-6250 are concerned about plagiarism of CS-6250 coursework, why not simply change your curriculum / tests / etc? Its been 6 years!  If you simply changed the content, you wouldn't have to worry about students open-sourcing their work (a practice that is so common now, I am truly dumbfounded as to why you are still asking students to make their repos private)
3. Your request to make repositories private but then provide access to prospective employers who **hopefully** have Github accounts does not sound like a solution at all. Many times employers will look at these repositories, prior to even interviewing therefore there is no chance to provide them access to private repos. 
4. Finally, the higher-learning and education space has way bigger 'fish to fry' with regard to plagiarism and the ever growing use of LLMs and AI assisted tooling. If anything Georgia Tech should be investing resources and effort into ways to prevent usage of AI assisted tools, rather than writing scripts to troll Github (the fish in the barrel approach). 

I wont be removing this work or making it private but I do wish you luck in your efforts to combat plagiarism. I hope my open-sourcing of CS-6250 coursework will make it that much easier for you to spot future plagiarism.
